GET http://localhost:3000/libros HTTP/1.1 

###
GET http://localhost:3000/libros/1 HTTP/1.1 
###

POST http://localhost:3000/libros HTTP/1.1
Content-Type: application/json

{
    "nombre":"Viaje al centro de la tierra",
    "autor":1,
    "año":1
}
###
PUT http://localhost:3000/libros/1 HTTP/1.1
Content-Type: application/json

{
    "nombre":"Harry Potter el caliz de fuego"
}

###
DELETE http://localhost:3000/libros/2 HTTP/1.1